### ISSUE TITLE
(Suggestion) Add AI command

### ISSUE THREAD

**Issue by InikoPro** [DodoGames7/Dodo-Bot#26]
There are API in OpenAI, SLX Universe AI, other.
In SLX Universe AI, very it's free and no sign up required. But i think openai is free or paid...

So you can add AI command, right?

**Comment by ddodogames** [comment]
It depends, for security purposes, if it requires an api key then i would not add it at all or at least, limit the api key to dev-owner commands in dms as anyone can use these for bad purposes.

Honestly, i'm not a fan of AI commands but i don't personally mind with ai chatbot-like unless it becomes an issue later as chatGPT has been abused several times even as far as making it say racist comments.

Regardless of how dangerous this might seem, this can technically be added but with a warning before the user proceeding to try them. Thanks for the suggestions anyways, i will see about it and choose wisely...

**Comment by ddodogames** [comment]
Free AI could get downtimes which isn't really new. However, it is worth noting that Dodo-Bot v1 had a history of a lot of broken commands because their apis simply stopped working or shutdown by their devs (which is why v2 tries to be api-less in recent development) so there's a chance that this won't be added into Dodo-Bot.

Also any free ai could stop existing at anytime so i don't want to have a broken command hiding somewhere in v2's files that it's api died because the free version is no longer offered to it's users.

With that being said, still, thank you for the suggestion but it won't be added into the bot anyways. Feel free to suggest anything else! Cya!
